name: Build & Deploy Client

on:
  workflow_dispatch: {}

jobs:
    buildAndDeployClient:
      name: Build client
      runs-on: ubuntu-latest
      steps:  
        
        - name: Checkout
          uses: actions/checkout@v2
        
        - name: Cache
          uses: actions/cache@v2
          with:
            path: Library
            key: Library-WebGL
            restore-keys: Library-WebGL
        
        - name: Build
          uses: game-ci/unity-builder@v2
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          with:
            targetPlatform: WebGL

        - name: Configure git
          run: |
              git config --global user.name "${{ vars.CI_COMMIT_AUTHOR}}"
              git config --global user.email "${{ vars.CI_COMMIT_EMAIL}}"

        - name: Clone repository
          run: |
              git clone "${{ secrets.REPOSITORY_URL }}" deployment
        
        - name: Copy build
          run: |
              cp -R build/WebGL deployment
        
        - name: Deploy
          run: |
              cd deployment
              git add .
              git commit -m "Deploy test"
              git push
