name: Build & Deploy

on:
  push:
    tags: "[0-9]+.[0-9]+.[0-9]+"

jobs:
    buildAndDeployClient:
      name: Build & deploy client
      uses: ./.github/workflows/build-deploy-client.yml
      secrets: inherit
    
    buildAndDeployServer:
      name: Build & deploy server
      uses: ./.github/workflows/build-deploy-server.yml
      secrets: inherit