name: Build & Deploy Client (Liberators' Test)

on:
  workflow_call: {}

env:
  BUILD_FULL_NAME: "${{ vars.BUILD_NAME }}_${{ github.ref_name }}"
  BUILD_TARGET: StandaloneWindows

jobs:
    buildAndDeployClient:
      name: Build & deploy
      runs-on: windows-2019
      steps:
        
        # Checkouts the current repository
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 1

        # Caches the Library folder for faster builds
        - name: Cache
          uses: actions/cache@v3
          with:
            path: Library
            key: Library-${{ env.BUILD_TARGET }}
            restore-keys: Library-
        
        # Builds the Windows client using a given license
        - name: Build
          uses: game-ci/unity-builder@v2
          env:
            UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
            UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          with:
            buildName: "${{ env.BUILD_FULL_NAME }}"
            targetPlatform: ${{ env.BUILD_TARGET }}
            versioning: None
            buildMethod: Digi.Utilities.Deploy.GameBuilderCI.Build
            customParameters: -scriptingBackend IL2CPP
        
        # Compresses the build folder as zip
        - name: Zip build
          uses: thedoctor0/zip-release@0.7.1
          with:
            directory: build/${{ env.BUILD_TARGET }}
            filename: ${{ env.BUILD_FULL_NAME }}.zip

        # Uploads the build to Google Drive
        - name: Upload to Google Drive
          uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v1.1.1
          with:
            target: build/${{ env.BUILD_TARGET }}/${{ env.BUILD_FULL_NAME }}.zip
            credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
            parent_folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}