name: Test LFS Check

on:
  workflow_dispatch: {}

env:
  BUILD_TARGET: StandaloneWindows

jobs:
    buildAndDeployClient:
      name: Build & deploy
      runs-on: ubuntu-latest
      steps:

        # Checkouts the current repository
        - name: Checkout
          uses: actions/checkout@v3
          with:
            fetch-depth: 1

        # Downloads LFS files if the project is using them
        - name: Check LFS download
          run: bash ${GITHUB_WORKSPACE}/.github/scripts/common/check-lfs-download.sh