name: Upload to Google Drive Test

on:
  workflow_dispatch: {}

env:
  TEST_FILE_NAME: "Test.txt"

jobs:
  uploadToDriveTest:
    name: Upload to Drive test
    runs-on: ubuntu-latest
    steps:

      - name: Create sample file
        run: |
          touch ${{ env.TEST_FILE_NAME }}
          echo "This is a sample text file." > ${{ env.TEST_FILE_NAME }}
      
      - name: Upload to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
          credentials: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_CREDENTIALS }}
          filename: ${{ env.TEST_FILE_NAME }}
          folderId: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
          name: ${{ env.TEST_FILE_NAME }} # optional string
          overwrite: "true" # optional boolean